fix(OpenStack): Do not raise exception when using unavailable network
In some cases when network has an outage or is temporarily
removed etc. mrack would raise an exception when getting
the "id" from network which is set to 'None' which is
obvious AttributeError: 'NoneType' object has no attribute 'get'

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>