fix: podman ansible inventory and status_map
Fixing ansible inventory generation for podman because db_host has no
attribute id.
Fixing AttributeError: 'PodmanProvider' object has no attribute 'strategy'.
Adding status map to podman

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>